import { Router } from "express";
import auth from "./auth.js";
import products from "./products.js";
import categories from "./categories.js";
import media from "./media.js";
import sets from "./sets.js";
import users from "./users.js";
import userDetails from "./userDetails.js";
import ordersRouter from "./orders.js";
import heroRoutes from "./heroes.js";
import shippingRoutes from "./shipping.js";
import discountRoutes from "./discounts.js";
import couponRoutes from "./coupons.js";
import campaignRoutes from "./campaigns.js";
import reviewRoutes from "./reviews.js";
import aboutRoutes from "./about.js";
import contactRoutes from "./contact.js";
import faqRoutes from "./faq.js";
import shippingReturnsRoute from "./shippingReturns.js";
import privacyRoutes from "./privacy.js";
import termsRoutes from "./terms.js";
import themeRoutes from "./theme.js";
import stocksRoutes from "./stocks.js";

const router = Router();

// ileride burada /products, /categories vs. mount edeceğiz
router.get("/health", (req, res) => res.json({ ok: true }));
router.use("/auth", auth);
router.use("/products", products);
router.use("/categories", categories);
router.use("/media", media);
router.use("/sets", sets);
router.use("/users", users);
router.use("/user-details", userDetails);
router.use("/orders", ordersRouter);
router.use("/heroes", heroRoutes);
router.use("/shipping", shippingRoutes);
router.use("/discounts", discountRoutes);
router.use("/coupons", couponRoutes);
router.use("/campaigns", campaignRoutes);
router.use("/reviews", reviewRoutes);
router.use("/about", aboutRoutes);
router.use("/contact", contactRoutes);
router.use("/faq", faqRoutes);
router.use("/shipping-returns", shippingReturnsRoute);
router.use("/privacy", privacyRoutes);
router.use("/terms", termsRoutes);
router.use("/theme", themeRoutes);
router.use("/stocks", stocksRoutes);

export default router;
