server {
    listen 80;
    listen [::]:80;
    server_name media.ceplife.com;

    root /srv/ceplife/media;
    autoindex off;
    access_log /var/log/nginx/media.ceplife.access.log;
    error_log /var/log/nginx/media.ceplife.error.log;
    sendfile on;
    tcp_nopush on;
    etag on;

    location / {
        limit_except GET HEAD OPTIONS { deny all; }
        add_header Cache-Control "public, max-age=31536000, immutable" always;
        add_header Access-Control-Allow-Origin "*" always;
        try_files $uri =404;
    }
}
