// src/theme/palettes.js
export const THEME_PRESETS = [
  {
    key: "rosewood",
    name: "Rosewood",
    store: {
      "--color-primary": "#5C2A35",
      "--color-secondary": "#8A4D5B",
      "--color-accent": "#D87C82",
      "--color-accent-hover": "#C4646D",
      "--color-surface": "#F0D9D9",
      "--color-surface-light": "#F9ECEC",
      "--color-surface-hover": "#FFF6F6",
      "--color-border": "#E1BFC2",
      "--color-contact-bg": "#FFF9F8",
    },
    admin: {
      "--color-bg-admin": "#FDF7F9",
      "--color-text-admin": "#3B0A24",
      "--color-bg-card": "#FFFFFF",
      "--color-bg-hover": "#FDE2E7",
      "--color-bg-sidebar": "#9D174D",
      "--color-text-sidebar": "#FFFFFF",
      "--color-text-admin-muted": "#6B7280",
      "--color-border-admin": "#FBCFE8",
    },
  },
  {
    key: "slate_mint",
    name: "Slate Mint",
    store: {
      "--color-primary": "#0F172A",
      "--color-secondary": "#334155",
      "--color-accent": "#10B981",
      "--color-accent-hover": "#0EA371",
      "--color-surface": "#F1F5F9",
      "--color-surface-light": "#F8FAFC",
      "--color-surface-hover": "#FFFFFF",
      "--color-border": "#E2E8F0",
      "--color-contact-bg": "#FFFFFF",
    },
    admin: {
      "--color-bg-admin": "#F8FAFC",
      "--color-text-admin": "#0F172A",
      "--color-bg-card": "#FFFFFF",
      "--color-bg-hover": "#ECFEF5",
      "--color-bg-sidebar": "#0F766E",
      "--color-text-sidebar": "#ECFEFF",
      "--color-text-admin-muted": "#64748B",
      "--color-border-admin": "#D1FAE5",
    },
  },
  {
    key: "amber_night",
    name: "Amber Night",
    store: {
      "--color-primary": "#111827",
      "--color-secondary": "#4B5563",
      "--color-accent": "#F59E0B",
      "--color-accent-hover": "#D97706",
      "--color-surface": "#F9FAFB",
      "--color-surface-light": "#FFFFFF",
      "--color-surface-hover": "#FFF7ED",
      "--color-border": "#E5E7EB",
      "--color-contact-bg": "#FFFBEB",
    },
    admin: {
      "--color-bg-admin": "#FFFBEB",
      "--color-text-admin": "#111827",
      "--color-bg-card": "#FFFFFF",
      "--color-bg-hover": "#FEF3C7",
      "--color-bg-sidebar": "#92400E",
      "--color-text-sidebar": "#FFF7ED",
      "--color-text-admin-muted": "#6B7280",
      "--color-border-admin": "#FDE68A",
    },
  },
  {
    key: "royal_blue",
    name: "Royal Blue",
    store: {
      "--color-primary": "#1E3A8A",
      "--color-secondary": "#3B82F6",
      "--color-accent": "#60A5FA",
      "--color-accent-hover": "#3B82F6",
      "--color-surface": "#EFF6FF",
      "--color-surface-light": "#F8FAFF",
      "--color-surface-hover": "#FFFFFF",
      "--color-border": "#DBEAFE",
      "--color-contact-bg": "#FFFFFF",
    },
    admin: {
      "--color-bg-admin": "#F8FAFF",
      "--color-text-admin": "#0B1F66",
      "--color-bg-card": "#FFFFFF",
      "--color-bg-hover": "#E0EAFF",
      "--color-bg-sidebar": "#1E3A8A",
      "--color-text-sidebar": "#EAF2FF",
      "--color-text-admin-muted": "#64748B",
      "--color-border-admin": "#C7D7FF",
    },
  },
  {
    key: "forest",
    name: "Forest",
    store: {
      "--color-primary": "#064E3B",
      "--color-secondary": "#065F46",
      "--color-accent": "#34D399",
      "--color-accent-hover": "#10B981",
      "--color-surface": "#ECFDF5",
      "--color-surface-light": "#F6FFF9",
      "--color-surface-hover": "#FFFFFF",
      "--color-border": "#D1FAE5",
      "--color-contact-bg": "#FFFFFF",
    },
    admin: {
      "--color-bg-admin": "#F3FFF8",
      "--color-text-admin": "#052E24",
      "--color-bg-card": "#FFFFFF",
      "--color-bg-hover": "#DCFCE7",
      "--color-bg-sidebar": "#064E3B",
      "--color-text-sidebar": "#ECFDF5",
      "--color-text-admin-muted": "#6B7280",
      "--color-border-admin": "#BBF7D0",
    },
  },
];

// Yardımcı: DOM'a uygulama
export function applyThemeVars({ store = {}, admin = {} } = {}) {
  const root = document.documentElement;
  Object.entries(store).forEach(([k, v]) => root.style.setProperty(k, v));
  Object.entries(admin).forEach(([k, v]) => root.style.setProperty(k, v));
}
